import 'slick-carousel/slick/slick.min.js';
import 'select2/dist/js/select2.min.js';
require('./bootstrap');
require('./home');
require('./all_courses');
require('./course_detail');
require('./documents');
require('./profile');
require('./review');
require('./management');
